spring:
  datasource: #database source 작성
    url: jdbc:mysql://localhost:3306/test1?characterEncoding=UTF-8 # 쿼리 스트링으로 UTF-8 인코딩 설정
    username: root
    password: ckdals
    driver-class-name: org.mariadb.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: create-drop # application 실행 시점에 기존 ddl 정보를 다 지우고 다시 실행시킨다.
    properties:
      hibernate:
#        show_sql: true # jpa, hibernate가 생성하는 모든 sql이 sout으로 찍힌다
                       # 운영환경에서는 sout이 아닌 log로 나타내야 한다
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 15MB

logging:
  level:
    org.springfrawork.web.socket.sockjs.* : trace # sockjs 통신에 대한 log
    org.hibernate.SQL: debug # jpa나 hibernate가 생성하는 모든 sql이 log에 남겨진다
    org.hibernate.type: trace
