spring:
  datasource: #database source 작성
    url: jdbc:mysql://139.150.76.155:3306/test?characterEncoding=UTF-8 # 쿼리 스트링으로 UTF-8 인코딩 설정
    username: root
    passowrd:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: none # 개발 초기 단계 create, 테스트 서버 update 또는 validate, 운영 서버 none
    properties:
      hibernate:
        #        show_sql: true # jpa, hibernate가 생성하는 모든 sql이 sout으로 찍힌다
        # 운영환경에서는 sout이 아닌 log로 나타내야 한다
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # jpa나 hibernate가 생성하는 모든 sql이 log에 남겨진다
    org.hibernate.type: trace
